import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:islamic_dawah_mushaf/page_span_data.dart';

/// Guards the page-spanning ayah table against output.json drifting under it.
///
/// Each key is a page whose *first* ayah starts on the page before — that is
/// what makes the page turn wait — so a re-cut page boundary that breaks the
/// relationship would leave the reader held on a page the recitation has
/// already left. The table is generated by tools/build_page_spans.py; re-run it
/// (with --remeasure) if this fails after an output.json change.
void main() {
  final pages = <int, List<Map<String, dynamic>>>{};

  setUpAll(() {
    final decoded = json.decode(
      File('assets/data/output.json').readAsStringSync(),
    );
    void add(Object? item) {
      if (item is List) {
        for (final sub in item) {
          add(sub);
        }
      } else if (item is Map<String, dynamic>) {
        pages[item['page'] as int] = (item['ayahs'] as List)
            .cast<Map<String, dynamic>>();
      }
    }

    add(decoded);
  });

  test(
    'every entry names a page whose first ayah starts on the page before',
    () {
      expect(spannedAyahHead, isNotEmpty);
      for (final page in spannedAyahHead.keys) {
        final here = pages[page];
        final before = pages[page - 1];
        expect(
          here,
          isNotNull,
          reason: 'page $page is missing from output.json',
        );
        expect(before, isNotNull, reason: 'page ${page - 1} is missing');
        expect(here!, isNotEmpty, reason: 'page $page lists no ayat');
        expect(before!, isNotEmpty, reason: 'page ${page - 1} lists no ayat');

        final first = here.first;
        final last = before.last;
        expect(
          first['surah'],
          last['surah'],
          reason:
              'page $page starts a different surah than page ${page - 1} ends',
        );
        expect(
          first['ayah'],
          (last['ayah'] as int) + 1,
          reason: 'page $page does not carry on from page ${page - 1}',
        );
      }
    },
  );

  test('every fraction leaves a real part of the ayah on each page', () {
    for (final entry in spannedAyahHead.entries) {
      // Below about a sixth the page turn is close enough to right already,
      // and the generator does not emit it; at 1.0 nothing of the ayah would
      // be left to read on the page turned to.
      expect(entry.value, greaterThan(0.15), reason: 'page ${entry.key}');
      expect(entry.value, lessThan(1.0), reason: 'page ${entry.key}');
    }
  });
}
