name: islamic_dawah_mushaf
description: "Mushaf Al-Dawah Al-Islamia Al-Jame."
publish_to: 'none'

version: 1.1.3+19

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  screen_brightness: ^2.1.9
  wakelock_plus: ^1.5.1
  share_plus: ^13.1.0
  url_launcher: ^6.3.1
  http: ^1.4.0
  path_provider: ^2.1.5
  archive: ^4.0.9
  crypto: ^3.0.6
  path: ^1.9.1
  in_app_review: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  audio_session: ^0.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1    

flutter_launcher_icons:              
  ios: true
  android: false
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/output.json
    - assets/data/ar.saddi.json
    - assets/data/narration_map.json
    - assets/data/ayah_positions.json
    - assets/data/audio_ayah_map.json
    - assets/data/qaniwah_continuations.json
  
