import 'dart:convert';

import 'package:flutter/foundation.dart' show compute, debugPrint, visibleForTesting;
import 'package:flutter/services.dart' show rootBundle;

import '../utils/phoneme_tracker.dart';

/// Expected phonemes of one mushaf page: per ayah (in page order), per word
/// (in reading order, parallel to the page text split on whitespace).
class PagePhonemes {
  const PagePhonemes({required this.page, required this.ayahKeys, required this.words});

  final int page;

  /// `surah:ayah` keys in page order.
  final List<String> ayahKeys;

  /// All words of the page in reading order with ayah index 0-based.
  final List<PhonemeWord> words;

  /// Words with madd runs collapsed, ready for [PhonemeReference].
  List<PhonemeWord> collapsed() => [
        for (final w in words)
          PhonemeWord(
            phon: collapseMadd(w.phon),
            text: w.text,
            ayah: w.ayah,
            wordInAyah: w.wordInAyah,
            ayahWords: w.ayahWords,
            tanween: w.tanween,
            taMarbuta: w.taMarbuta,
            hafsAlt: collapseMadd(w.hafsAlt),
            wasl: w.wasl,
            alts: [for (final a in w.alts) collapseMadd(a)],
            accept: [for (final a in w.accept) collapseMadd(a)],
          ),
      ];
}

/// Loads `assets/data/page_phonemes.json` (generated by
/// `tasmee_work/zipformer/eval_session.py`'s page builder: Qalun words of
/// every page paired by text with the Quran-Lab / Tilawa Hafs phoneme
/// lexicon). Same lazy, isolate-parsed, cached pattern as
/// `WordRegionService`.
class PagePhonemeService {
  static const String _assetPath = 'assets/data/page_phonemes.json';
  static Map<int, PagePhonemes>? _cache;
  static Future<Map<int, PagePhonemes>>? _loading;

  static Future<Map<int, PagePhonemes>> loadAll() {
    if (_cache != null) return Future.value(_cache!);
    return _loading ??= _load().whenComplete(() => _loading = null);
  }

  static Future<Map<int, PagePhonemes>> _load() async {
    try {
      final jsonString = await rootBundle.loadString(_assetPath);
      _cache = await compute(parse, jsonString);
    } catch (error) {
      debugPrint('PagePhonemeService: failed to load $_assetPath: $error');
      _cache = const {};
    }
    return _cache!;
  }

  @visibleForTesting
  static Map<int, PagePhonemes> parse(String jsonString) {
    final decoded = json.decode(jsonString) as List<dynamic>;
    final out = <int, PagePhonemes>{};
    for (final item in decoded) {
      final m = item as Map<String, dynamic>;
      final page = m['page'] as int;
      final keys = <String>[];
      final words = <PhonemeWord>[];
      final ayahs = m['ayahs'] as List<dynamic>;
      for (var a = 0; a < ayahs.length; a++) {
        final ay = ayahs[a] as Map<String, dynamic>;
        keys.add(ay['key'] as String);
        final ws = ay['w'] as List<dynamic>;
        for (var i = 0; i < ws.length; i++) {
          final w = ws[i] as List<dynamic>;
          words.add(PhonemeWord(
            text: w[0] as String,
            phon: w[1] as String,
            tanween: w.length > 2 ? w[2] as String : '',
            taMarbuta: w.length > 3 && (w[3] as num) != 0,
            hafsAlt: w.length > 4 ? w[4] as String : '',
            wasl: w.length > 5 && (w[5] as num) != 0,
            alts: w.length > 6
                ? (w[6] as List<dynamic>).cast<String>()
                : const [],
            accept: w.length > 7
                ? (w[7] as List<dynamic>).cast<String>()
                : const [],
            ayah: a,
            wordInAyah: i,
            ayahWords: ws.length,
          ));
        }
      }
      out[page] = PagePhonemes(page: page, ayahKeys: keys, words: words);
    }
    return out;
  }

  static Future<PagePhonemes?> forPage(int page) async => (await loadAll())[page];

  /// The mushaf spelling of a word heard as the phoneme string [phon] (a
  /// lexicon form the judge matched), or null when no word of the mushaf is
  /// pronounced that way. Built once from every word of every page; where
  /// several spellings share a pronunciation the most frequent one wins.
  static String? textFor(String phon) {
    final cache = _cache;
    if (cache == null) return null;
    final map = _textByPhon ??= _buildTextMap(cache);
    return map[collapseMadd(phon)];
  }

  static Map<String, String>? _textByPhon;

  static Map<String, String> _buildTextMap(Map<int, PagePhonemes> pages) {
    final counts = <String, Map<String, int>>{};
    for (final page in pages.values) {
      for (final w in page.words) {
        final key = collapseMadd(w.phon);
        final byText = counts[key] ??= {};
        byText[w.text] = (byText[w.text] ?? 0) + 1;
      }
    }
    return {
      for (final e in counts.entries)
        e.key: (e.value.entries.toList()
              ..sort((a, b) => b.value.compareTo(a.value)))
            .first
            .key,
    };
  }
}
