// Exact page-turn moments inside the ayat printed across a page break —
// لحظة قلب الصفحة داخل الآيات الممتدة بين صفحتين.
//
// Generated by tools/measure_page_turn_cues.py — do not edit by hand.
// Re-run it for a reciter whenever that reciter's audio changes, and for
// a new reciter before it ships (test/page_turn_cues_test.dart insists).

import 'page_span_data.dart';

/// The moment, in one reciter's audio, at which the last word printed on
/// the earlier page has been recited.
///
/// [file] is the audio file as the app names it (`SSSAAA.mp3` for the
/// per-ayah mirrors, `SSS.mp3` for [AudioScheme.timedSurah]) and [atMs] a
/// position inside that whole file — under the timed scheme the player
/// holds the whole surah, so it is not an offset from the ayah's span.
///
/// ([surah], [ayah]) is the displayed ayah whose clip plays that file: the
/// page-spanning ayah itself, or — for a sheikh who reads it inside the
/// previous ayah's breath — that previous ayah, which is listed on the
/// earlier page. The page then turns mid-way through *its* clip.
class PageTurnCue {
  const PageTurnCue(this.surah, this.ayah, this.file, this.atMs);

  final int surah;
  final int ayah;
  final String file;
  final int atMs;
}

/// Reciter id → page turned to (a key of [spannedAyahHead]) → its cue.
const Map<String, Map<int, PageTurnCue>> pageTurnCues = {
  'husary_qaloun': {
    // 2:218 «والاخرة», pause 2.04s.
    35: PageTurnCue(2, 218, '002218.mp3', 24290),
    // 4:44 «السبيل», pause 3.37s.
    86: PageTurnCue(4, 44, '004044.mp3', 19610),
    // 14:27 «السماء», pause 3.05s.
    259: PageTurnCue(14, 27, '014027.mp3', 25070),
    // 24:36 «والاصال», read on, dip -15 dB.
    355: PageTurnCue(24, 36, '024036.mp3', 21440),
    // 24:42 «بالابصار», pause 1.44s.
    356: PageTurnCue(24, 42, '024042.mp3', 72240),
  },
  'naihi_qaloun': {
    // 2:218 «والاخرة», pause 0.82s.
    35: PageTurnCue(2, 218, '002.mp3', 5044020),
    // 4:44 «السبيل», pause 0.70s.
    86: PageTurnCue(4, 44, '004.mp3', 1339820),
    // 14:27 «السماء», read on, dip -15 dB.
    259: PageTurnCue(14, 27, '014.mp3', 504530),
    // 24:36 «والاصال», pause 0.87s.
    355: PageTurnCue(24, 36, '024.mp3', 756020),
    // 24:42 «بالابصار», pause 0.60s.
    356: PageTurnCue(24, 42, '024.mp3', 914360),
  },
  'qaniwah_qaloun': {
    // 2:218 «والاخرة», pause 1.71s — read inside 2:217.
    35: PageTurnCue(2, 217, '002217.mp3', 42540),
    // 4:44 «السبيل», pause 1.09s.
    86: PageTurnCue(4, 44, '004044.mp3', 16180),
    // 14:27 «السماء», read on, dip -26 dB.
    259: PageTurnCue(14, 27, '014027.mp3', 19820),
    // 24:36 «والاصال», read on.
    355: PageTurnCue(24, 36, '024036.mp3', 14420),
    // 24:42 «بالابصار», pause 0.96s.
    356: PageTurnCue(24, 42, '024042.mp3', 47280),
  },
  'hudaifi_qaloun': {
    // 2:218 «والاخرة», pause 1.19s — read inside 2:217.
    35: PageTurnCue(2, 217, '002217.mp3', 35850),
    // 4:44 «السبيل», pause 1.01s.
    86: PageTurnCue(4, 44, '004044.mp3', 13230),
    // 14:27 «السماء», pause 0.98s.
    259: PageTurnCue(14, 27, '014027.mp3', 16900),
    // 24:36 «والاصال», pause 1.06s.
    355: PageTurnCue(24, 36, '024036.mp3', 13270),
    // 24:42 «بالابصار», pause 1.21s.
    356: PageTurnCue(24, 42, '024042.mp3', 51020),
  },
  'doukali_qaloun': {
    // 2:218 «والاخرة», pause 2.17s — read inside 2:217.
    35: PageTurnCue(2, 217, '002217.mp3', 32740),
    // 4:44 «السبيل», pause 1.52s.
    86: PageTurnCue(4, 44, '004044.mp3', 12530),
    // 14:27 «السماء», read on, dip -22 dB.
    259: PageTurnCue(14, 27, '014027.mp3', 14760),
    // 24:36 «والاصال», pause 2.10s.
    355: PageTurnCue(24, 36, '024036.mp3', 13080),
    // 24:42 «بالابصار», read on.
    356: PageTurnCue(24, 42, '024042.mp3', 47930),
  },
  'alqryw_qaloun': {
    // 2:218 «والاخرة», pause 1.33s.
    35: PageTurnCue(2, 218, '002.mp3', 5481800),
    // 4:44 «السبيل», pause 1.02s.
    86: PageTurnCue(4, 44, '004.mp3', 1478900),
    // 14:27 «السماء», pause 1.24s.
    259: PageTurnCue(14, 27, '014.mp3', 560980),
    // 24:36 «والاصال», read on.
    355: PageTurnCue(24, 36, '024.mp3', 993280),
    // 24:42 «بالابصار», pause 1.27s.
    356: PageTurnCue(24, 42, '024.mp3', 1214830),
  },
  'abusenainah_qaloun': {
    // 2:218 «والاخرة», pause 0.43s — read inside 2:217.
    35: PageTurnCue(2, 217, '002.mp3', 5702400),
    // 4:44 «السبيل», pause 0.81s.
    86: PageTurnCue(4, 44, '004.mp3', 1422950),
    // 14:27 «السماء», read on, dip -19 dB.
    259: PageTurnCue(14, 27, '014.mp3', 641810),
    // 24:36 «والاصال», pause 1.07s.
    355: PageTurnCue(24, 36, '024.mp3', 890910),
    // 24:42 «بالابصار», read on, stop 0.12s.
    356: PageTurnCue(24, 42, '024.mp3', 1093260),
  },
  'rajab_qaloun': {
    // 2:218 «والاخرة», pause 1.18s.
    35: PageTurnCue(2, 218, '002.mp3', 5114100),
    // 4:44 «السبيل», pause 0.75s.
    86: PageTurnCue(4, 44, '004.mp3', 1328710),
    // 14:27 «السماء», pause 0.27s.
    259: PageTurnCue(14, 27, '014.mp3', 616930),
    // 24:36 «والاصال», read on, dip -12 dB.
    355: PageTurnCue(24, 36, '024.mp3', 878270),
    // 24:42 «بالابصار», pause 1.04s.
    356: PageTurnCue(24, 42, '024.mp3', 1087090),
  },
};
