// Ayat printed across a page break — آيات ممتدة بين صفحتين.
//
// assets/data/output.json lists an ayah under the page its rosette is printed
// on, so an ayah running across the break belongs to the page it *ends* on. The
// reader, though, is still looking at the page it *starts* on, and turning the
// page the moment such an ayah begins throws them forward off words still in
// front of them.
//
// Keyed by the page the ayah is listed on (the page being turned to); the value
// is the fraction of that ayah's recitation printed on the page before it — how
// long the turn waits. This mushaf breaks its pages at an ayah end everywhere
// else, which is why there are so few.
//
// Each value is where the reciters are actually heard to reach the break: their
// pauses are timed against the ayah's waqf stops and the median taken, which
// they agree on inside a few per cent. It falls back to an estimate from the
// printed page and the letter count where the break carries no waqf mark and
// most sheikhs read straight past it.
//
// Generated by tools/build_page_spans.py (and tools/measure_page_span_pauses.py
// for the timings) — do not edit by hand.
const Map<int, double> spannedAyahHead = {
  // 2:218 — page 34 ends at «والاخرة»; median of 3 reciters.
  35: 0.328,
  // 4:44 — page 85 ends at «السبيل»; median of 7 reciters.
  86: 0.491,
  // 14:27 — page 258 ends at «السماء»; median of 5 reciters.
  259: 0.481,
  // 24:36 — page 354 ends at «والاصال»; estimated from the page and the text.
  355: 0.399,
  // 24:42 — page 355 ends at «بالابصار»; median of 7 reciters.
  356: 0.758,
};
