"""Generate lib/models/doukali_covered_ayat.dart from the web player's data.

الدوكالي محمد العالم's khatma was cut per-ayah with the same pipeline as the
Hudaifi set: file `SSSAAA.mp3` is the displayed ayah, and every ayah he reads
inside a neighbouring ayah's file gets a silent 1579-byte placeholder. The
canonical covered-ayah list lives in the web player source page
(https://audio.mushaf-qaloon.com/mushaf_doukali.html); this script reuses the
already-flattened web-player/data/overrides_doukali.json that
build_web_player_data.py builds from it, so run that first if the source
changed.

Usage (from the repo root):
    python tools/gen_doukali_covered_ayat.py
Then let `dart format lib/models/doukali_covered_ayat.dart` settle the layout.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OVERRIDES = ROOT / "web-player" / "data" / "overrides_doukali.json"
OUT = ROOT / "lib" / "models" / "doukali_covered_ayat.dart"

EXPECTED_COUNT = 1194  # matches build_web_player_data.py's assertion


def main() -> None:
    overrides = json.loads(OVERRIDES.read_text(encoding="utf-8"))["overrides"]

    covered: dict[int, list[int]] = {}
    for key, entry in overrides.items():
        # Every doukali override is a pure covered entry; anything else means
        # the cut changed shape and this generator (and the app's scheme
        # choice) must be revisited, not silently skipped.
        assert entry.get("f") == [] and entry.get("cov"), f"unexpected entry {key}: {entry}"
        surah, ayah = map(int, key.split("-"))
        cov_surah, cov_ayah = map(int, entry["cov"].split("-"))
        assert cov_surah == surah and cov_ayah < ayah, f"non-backward cover {key} -> {entry['cov']}"
        covered.setdefault(surah, []).append(ayah)

    total = sum(len(v) for v in covered.values())
    assert total == EXPECTED_COUNT, f"covered count changed: {total}"

    lines = [
        "// GENERATED by tools/gen_doukali_covered_ayat.py — do not edit by hand.",
        "// Source: web-player/data/overrides_doukali.json (itself built from",
        "// https://audio.mushaf-qaloon.com/mushaf_doukali.html by",
        "// tools/build_web_player_data.py).",
        "",
        "/// Ayat whose الدوكالي محمد العالم file carries no recitation: a silent",
        "/// 1579-byte placeholder, because the sheikh reads the verse inside a",
        f"/// neighbouring ayah's file. {total} entries, verified against the live",
        "/// bucket by sampling placeholder sizes. See [Reciter.doukaliQaloun].",
        "const Map<int, Set<int>> doukaliCoveredAyat = {",
    ]
    for surah in sorted(covered):
        ayat = ", ".join(str(a) for a in sorted(covered[surah]))
        lines.append(f"  {surah}: {{{ayat}}},")
    lines.append("};")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({total} covered ayat over {len(covered)} surahs)")


if __name__ == "__main__":
    main()
