"""Emit lib/data/page_crops.dart from assets/data/word_masks.json + the pages.

Every page image bundled with the app is the full هوامش (margin) scan. When the
margin view is off the reader shows only the frame interior, and this file is
where it learns where that interior sits:

* the `hw` rect of each page (ratios of the margin image — the same numbers
  the margin-view overlays use, so the crop and the overlays can never
  disagree);
* the paper colour of the page (`paper`), used to fill the sliver where page
  1's rect runs past the image edge and to paint the edge trims;
* per-edge trims. The `hw` rects were fitted on the text, not on the frame,
  so on most pages the frame's black line lands a few pixels inside the crop.
  The trim is how deep that line reaches from each edge (as a ratio of the
  crop), so the reader can paint paper over it. Nothing but the frame line
  and the margin outside it ever lies in that strip.

Needs Pillow and numpy. Run from the repo root after any refit of
hawamesh_transform.json has been folded into word_masks.json, or after any
page image in assets/images/ is replaced:

    python tools/generate_page_crops.py
"""
import json
import os

import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'assets', 'data', 'word_masks.json')
IMAGES = os.path.join(ROOT, 'assets', 'images', 'page_%d.webp')
DST = os.path.join(ROOT, 'lib', 'data', 'page_crops.dart')

# How far in from each crop edge to look for the frame line, in scan pixels.
SEARCH_DEPTH = 16
# A column/row is "frame line" when this share of it is dark. Text never
# comes close: the densest text column is well under a quarter dark.
LINE_DARK_SHARE = 0.45
DARK = 150
# Pixels added past the line's inner edge to cover its anti-aliased fringe.
FRINGE = 2
# The opening spread has an ornamental border instead of the frame; it is
# shown as it is in both views.
UNFRAMED_PAGES = (1, 2)


def edge_trims(page, hw):
    """Depth of the frame line from each crop edge, in scan pixels (L,T,R,B)."""
    if page in UNFRAMED_PAGES:
        return (0, 0, 0, 0), None
    scan = Image.open(IMAGES % page).convert('L')
    sw, sh = scan.size
    x, y, w, h = hw
    box = (round(x * sw), round(y * sh), round((x + w) * sw), round((y + h) * sh))
    cw, ch = box[2] - box[0], box[3] - box[1]
    canvas = Image.new('L', (cw, ch), 255)
    canvas.paste(scan, (-box[0], -box[1]))
    dark = np.asarray(canvas) < DARK
    cols = dark.mean(0)
    rows = dark.mean(1)

    def depth(share):
        hits = [i for i in range(SEARCH_DEPTH) if share[i] > LINE_DARK_SHARE]
        return max(hits) + 1 + FRINGE if hits else 0

    return (depth(cols), depth(rows), depth(cols[::-1]), depth(rows[::-1])), (cw, ch)


def main():
    pages = json.load(open(SRC, encoding='utf-8'))
    by_page = {p['page']: p for p in pages}
    assert sorted(by_page) == list(range(1, 603)), 'expected pages 1..602'

    lines = [
        '// GENERATED by tools/generate_page_crops.py from assets/data/word_masks.json',
        '// and the page images. Do not edit by hand.',
        '',
        "import 'dart:ui' show Color, Rect;",
        '',
        "/// Where the frame interior of a page sits inside its full هوامش scan, as",
        '/// ratios of that scan. These are the same `hw` rects the margin-view',
        '/// overlays use, so the crop shown when the margin view is off and the',
        '/// overlays drawn when it is on always agree.',
        'class PageCrop {',
        '  const PageCrop(',
        '    this.left,',
        '    this.top,',
        '    this.width,',
        '    this.height,',
        '    this.paper, [',
        '    this.trimLeft = 0,',
        '    this.trimTop = 0,',
        '    this.trimRight = 0,',
        '    this.trimBottom = 0,',
        '  ]);',
        '',
        '  final double left;',
        '  final double top;',
        '  final double width;',
        '  final double height;',
        '',
        '  /// Paper colour of the page.',
        '  final Color paper;',
        '',
        "  /// How far the frame's line reaches into the crop from each edge, as a",
        '  /// ratio of the crop\'s width (left/right) or height (top/bottom). Zero',
        '  /// where the line falls outside the crop.',
        '  final double trimLeft;',
        '  final double trimTop;',
        '  final double trimRight;',
        '  final double trimBottom;',
        '',
        '  Rect get rect => Rect.fromLTWH(left, top, width, height);',
        '',
        '  /// Crop for a 1-based [page]; every page has one.',
        '  static PageCrop forPage(int page) => kPageCrops[page - 1];',
        '}',
        '',
        '/// Index 0 is page 1.',
        'const List<PageCrop> kPageCrops = <PageCrop>[',
    ]
    deepest = [0, 0, 0, 0]
    trimmed = [0, 0, 0, 0]
    for n in range(1, 603):
        p = by_page[n]
        x, y, w, h = p['hw']
        r, g, b = p['paper']
        px, size = edge_trims(n, p['hw'])
        head = 'PageCrop(%.5f, %.5f, %.5f, %.5f, Color(0xFF%02X%02X%02X)' % (
            x, y, w, h, r, g, b)
        if any(px):
            cw, ch = size
            ratios = (px[0] / cw, px[1] / ch, px[2] / cw, px[3] / ch)
            head += ', ' + ', '.join('%.5f' % v for v in ratios)
            for i in range(4):
                deepest[i] = max(deepest[i], px[i])
                trimmed[i] += 1 if px[i] else 0
        lines.append('  %s), // %d' % (head, n))
    lines += ['];', '']
    os.makedirs(os.path.dirname(DST), exist_ok=True)
    with open(DST, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print('wrote', DST, 'with', len(by_page), 'pages')
    print('pages trimmed per edge (L,T,R,B):', trimmed, 'deepest px:', deepest)


if __name__ == '__main__':
    main()
